package Configurations

var OzgecmisServiceUrl string = "http://servisler.yok.gov.tr/ws/OzgecmisV2?wsdl"
var BapServiceUrl string = "http://servisler.yok.gov.tr/ws/OzgecmisBapV2?wsdl"
var UserId string = "Id"
var Password string = "Sifre"

// Soap adlari

var GetArastirmaSertifikaBilgisiv1Name string = "getArastirmaSertifkaBilgisiV1Request"
var GetBildiriBilgisiv1Name string = "getBildiriBilgisiV1Request"
var GetBildiriBilgisiDetayv1Name string = "getBildiriBilgisiDetayV1Request"
var GetEditorlukBilgisiv1Name string = "getEditorlukBilgisiV1Request"
var GetHakemlikBilgisiV1Name string = "getHakemlikBilgisiV1Request"
var GetirAkademikGorevListesiName string = "getirAkademikGorevListesiRequest"
var GetirAtifSayilariName string = "getirAtifSayilariRequest"
var GetirBasvuruDurumName string = "getirBasvuruDurumRequest"
var GetirBeyanTesvikName string = "getirBeyanTesvikRequest"
var GetirDersListesiName string = "getirDersListesiRequest"
var GetirIdariGorevListesiName string = "getirIdariGorevListesiRequest"
var GetirOgrenimBilgisiListesiName string = "getirOgrenimBilgisiListesiRequest"
var GetirProjeListesiName string = "getirProjeListesiRequest"
var GetirProjeListesiDetayName string = "getirProjeListesiDetayRequest"
var GetirTezDanismanListesiName string = "getirTezDanismanListesiRequest"
var GetirUnvDisiDeneyimListesiName = "getirUnvDisiDeneyimListesiRequest"
var GetirUyelikListesiName string = "getirUyelikListesiRequest"
var GetirYabanciDilListesi string = "getirYabanciDilListesiRequest"
var GetKitapBilgisiv1Name string = "getKitapBilgisiV1Request"
var GetKitapBilgisiDetayName string = "getKitapBilgisiDetayV1Request"
var GetMakaleBilgisiv1Name string = "getMakaleBilgisiV1Request"
var GetMakaleBilgisiDetayv1Name string = "getMakaleBilgisiDetayV1Request"
var GetOdulListesiv1Name string = "getOdulListesiV1Request"
var GetPatentBilgisiv1Name string = "getPatentBilgisiV1Request"
var GetPatentBilgisiDetayv1Name string = "getPatentBilgisiDetayV1Request"
var GetPersonelLinkv1Name string = "getPersonelLinkV1Request"
var GetSanatsalFaalv1Name string = "getSanatsalFaalV1Request"
var GetTasarimBilgisiv1Name string = "getTasarimBilgisiV1Request"
var GetTemelAlanBilgisiv1Name string = "getTemelAlanBilgisiV1Request"
var GetTesvikKatsayisiName string = "getTesvikKatsayiRequest"
var GetYazarListesiv1Name string = "getYazarListesiV1Request"

var BapProjeBilgiName string = "getBapProjeBilgiRequest"
var BapProjeEkipBilgisiName string = "getBapProjeEkipListeRequest"
var BapInsertOrUpdateRequestName string = "insertOrUpdateBapProjeRequest"
var BapDeleteBapProjeOrEkipName string = "deleteBapProjeOrEkipRequest"
var BapInsertOrUpdateProjeEkipName string = "insertOrUpdateBapProjeEkipRequest"

//////////////////////////////////////////////////////////////////
var ServiceResultSuccessName = "Success"
